import {useEffect,useState} from 'react';
import {api,errorMessage} from '../lib/api';
import {Button,Spinner} from '../components/ui';
export const money=(v:any)=>`Q ${Number(v||0).toFixed(2)}`;
export async function downloadPdf(url:string,name:string){const r=await api.get(url,{responseType:'blob'});const href=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=href;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
export default function Cash(){
 const [session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[amount,setAmount]=useState(''),[register,setRegister]=useState('CAJA 1'),[notes,setNotes]=useState(''),[closed,setClosed]=useState<any>(null);
 const [rows,setRows]=useState<any[]>([]),[period,setPeriod]=useState('day'),[date,setDate]=useState(()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Guatemala'}));
 const query=`period=${period}&date=${date}`;
 const load=async()=>{setError('');try{const [s,r]=await Promise.all([api.get('/cash/current'),api.get('/cash/report?'+query)]);setSession(s.data);setRows(r.data);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[period,date]);
 async function submit(){if(amount.trim()===''||!Number.isFinite(Number(amount))||Number(amount)<0){setError('Ingresa un monto válido, puede ser cero.');return;}setBusy(true);setError('');try{if(session){const r=await api.post(`/cash/${session.id}/close`,{countedCash:Number(amount),notes});setClosed(r.data);}else{await api.post('/cash/open',{registerName:register,openingCash:Number(amount)});setClosed(null);}setAmount('');setNotes('');await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 if(loading)return <Spinner/>;
 return <div><div className="page-head"><div><h1>Caja y turnos</h1><p>Abre tu caja antes de vender y realiza el cuadre al terminar.</p></div><Button variant="secondary" onClick={()=>void load()}>Actualizar</Button></div>
 {error&&<p role="alert">{error}</p>}
 <section className="panel" style={{padding:24,marginBottom:20}}><h2>{session?`Cerrar ${session.registerName}`:'Aperturar caja'}</h2>
 {session?<div className="stat-grid">{[['Fondo inicial',session.openingCash],['Ventas en efectivo',session.totals.CASH],['Ventas con tarjeta',session.totals.CARD],['Transferencias',session.totals.TRANSFER],['Efectivo esperado en caja',session.expectedCash]].map(([label,v])=><div className="stat-card" key={label}><h4>{label}</h4><strong>{money(v)}</strong></div>)}</div>:<label className="field"><span>Nombre de caja / POS</span><input maxLength={40} value={register} onChange={e=>setRegister(e.target.value)} /></label>}
 <label className="field"><span>{session?'Efectivo total contado al cerrar (Q)':'Efectivo actual / fondo inicial (Q)'}</span><input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label>
 {session&&<><label className="field"><span>Observaciones</span><input maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{amount!==''&&<p>Diferencia: {money(Number(amount)-session.expectedCash)} (positivo = sobrante; negativo = faltante).</p>}</>}
 <Button loading={busy} disabled={busy} onClick={()=>void submit()}>{session?'Confirmar cierre de caja':'Abrir caja'}</Button></section>
 {closed&&<section className="panel" style={{padding:24,marginBottom:20}}><h3>Cierre guardado</h3><p>Inicial: {money(closed.openingCash)} · Efectivo: {money(closed.cashSales)} · Tarjeta: {money(closed.cardSales)} · Transferencias: {money(closed.transferSales)}</p><p>Esperado: {money(closed.expectedCash)} · Contado: {money(closed.countedCash)} · Diferencia: {money(closed.difference)}</p></section>}
 <section className="panel" style={{padding:24}}><h3>Historial y reportes de caja</h3><p>Filtrado por fecha de apertura. Administradores: todas las cajas; cajeros: sus propios turnos.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginBottom:20}}><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="day">Día</option><option value="week">Semana (lunes a domingo)</option><option value="month">Mes</option></select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><Button onClick={()=>downloadPdf('/cash/report/pdf?'+query,'reporte-cajas.pdf').catch(e=>setError(errorMessage(e)))}>Descargar PDF</Button></div>
 {!rows.length?<p>No hay turnos en este período.</p>:rows.map(s=><div key={s.id} style={{borderTop:'1px solid var(--border)',padding:'16px 0'}}><strong>{s.registerName} · {s.user.name} · {s.closedAt?'Cerrada':'Abierta'}</strong><p>{new Date(s.openedAt).toLocaleString('es-GT',{timeZone:'America/Guatemala'})}</p><p>Inicial {money(s.openingCash)} · Efectivo {money(s.closedAt?s.cashSales:s.totals.CASH)} · Tarjeta {money(s.closedAt?s.cardSales:s.totals.CARD)} · Transferencias {money(s.closedAt?s.transferSales:s.totals.TRANSFER)}</p><p>Esperado {money(s.expectedCash)} · Contado {s.closedAt?money(s.countedCash):'Pendiente'} · Diferencia {s.closedAt?money(s.difference):'Pendiente'}</p></div>)}</section></div>;
}
