import {Banknote,CreditCard,ArrowUpRight,Download,Receipt,Wallet,CalendarDays} from 'lucide-react';
import {useEffect,useState} from 'react';
import {api,errorMessage} from '../lib/api';
import {Button,Spinner} from '../components/ui';
import {downloadPdf,money} from './Cash';
export default function Reports(){const [sales,setSales]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[period,setPeriod]=useState('day'),[date,setDate]=useState(()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Guatemala'}));const query=`period=${period}&date=${date}`;
useEffect(()=>{let active=true;setLoading(true);setError('');api.get('/reports/sales?'+query).then(r=>{if(active)setSales(r.data);}).catch(e=>{if(active)setError(errorMessage(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query]);
const totals={CASH:0,CARD:0,TRANSFER:0,total:0};for(const s of sales){let received=0;for(const p of s.payments){const v=Math.round(Number(p.amount)*100);totals[p.method as 'CASH'|'CARD'|'TRANSFER']+=v;received+=v;}totals.CASH-=Math.max(0,received-Math.round(Number(s.total)*100));totals.total+=Math.round(Number(s.total)*100);}
const methods=[{key:'CASH',label:'Efectivo',icon:Banknote,color:'#38947b'},{key:'CARD',label:'Tarjeta',icon:CreditCard,color:'#6079d3'},{key:'TRANSFER',label:'Transferencia',icon:ArrowUpRight,color:'#bc8a43'}] as const;
return <div className="report-page"><div className="page-head"><div><span className="eyebrow">RESUMEN DEL NEGOCIO</span><h1>Reportes de ventas</h1><p>Todos los números de tu negocio, en un solo lugar.</p></div><Button onClick={()=>downloadPdf('/reports/sales/pdf?'+query,'reporte-ventas.pdf').catch(e=>setError(errorMessage(e)))}><Download size={17}/>Descargar PDF</Button></div>
<div className="report-filters"><div><CalendarDays size={19}/><strong>Período del reporte</strong></div><select aria-label="Período" value={period} onChange={e=>setPeriod(e.target.value)}><option value="day">Por día</option><option value="week">Por semana</option><option value="month">Por mes</option></select><input aria-label="Fecha del reporte" type="date" value={date} onChange={e=>setDate(e.target.value)}/><span>Horario de Guatemala</span></div>
{error&&<p role="alert">{error}</p>}{loading?<Spinner/>:<><div className="report-summary"><div className="report-hero"><span><Wallet size={18}/>VENTAS DEL PERÍODO</span><strong>{money(totals.total/100)}</strong><p>{sales.length} {sales.length===1?'venta registrada':'ventas registradas'}</p><div>Ticket promedio <b>{money(sales.length?totals.total/100/sales.length:0)}</b></div></div><div className="report-method-cards">{methods.map(m=><div className="report-method" key={m.key}><div className="report-icon" style={{color:m.color,background:m.color+'18'}}><m.icon size={21}/></div><span>{m.label}</span><strong>{money(totals[m.key]/100)}</strong><small>{totals.total?(totals[m.key]/totals.total*100).toFixed(1):'0.0'}% de las ventas</small></div>)}</div></div>
<div className="report-distribution panel"><div><h3>Distribución de ingresos</h3><p>Efectivo neto después de entregar el cambio.</p></div><div className="report-bar">{methods.map(m=><div key={m.key} style={{width:`${totals.total?totals[m.key]/totals.total*100:0}%`,background:m.color}} title={`${m.label}: ${money(totals[m.key]/100)}`}/>)}</div><div className="report-legend">{methods.map(m=><span key={m.key}><i style={{background:m.color}}/>{m.label}<b>{money(totals[m.key]/100)}</b></span>)}</div></div>
<section className="panel report-table"><div className="panel-head"><div><h3>Detalle de ventas</h3><span>Operaciones del período seleccionado</span></div><span className="report-count">{sales.length} registros</span></div>{!sales.length?<div className="report-empty"><Receipt size={34}/><h3>Aún no hay ventas</h3><p>Selecciona otra fecha para consultar tus operaciones.</p></div>:<div style={{overflowX:'auto'}}><table><thead><tr><th>Venta / fecha</th><th>Cliente</th><th>Cajero</th><th>Métodos</th><th style={{textAlign:'right'}}>Total</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td><strong>#{s.id.slice(-8).toUpperCase()}</strong><small>{new Date(s.createdAt).toLocaleString('es-GT',{timeZone:'America/Guatemala'})}</small></td><td>{s.customer.name}</td><td>{s.user.name}</td><td><div className="report-pills">{Array.from(new Set<string>(s.payments.map((p:any)=>p.method))).map(k=><span key={k}>{methods.find(m=>m.key===k)?.label||k}</span>)}</div></td><td style={{textAlign:'right'}}><strong>{money(s.total)}</strong></td></tr>)}</tbody></table></div>}</section></>}</div>;}
